# Generated by Django 5.0.6 on 2026-03-31 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveStatusEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_turns', models.IntegerField(blank=True, help_text='Null means indefinite. Decremented each turn.', null=True)),
                ('applied_at_round', models.PositiveIntegerField()),
                ('turns_active', models.PositiveIntegerField(default=0, help_text='Incremented each turn; used for escalating effects.')),
            ],
            options={
                'verbose_name': 'active status effect',
                'verbose_name_plural': 'active status effects',
            },
        ),
        migrations.CreateModel(
            name='StatusEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(choices=[('burned', 'Burned'), ('poisoned', 'Poisoned'), ('badly_poisoned', 'Badly Poisoned'), ('paralyzed', 'Paralyzed'), ('frozen', 'Frozen'), ('asleep', 'Asleep'), ('confused', 'Confused'), ('infatuated', 'Infatuated'), ('flinched', 'Flinched'), ('bound', 'Bound'), ('seeded', 'Seeded'), ('cursed', 'Cursed'), ('nightmare', 'Nightmare'), ('taunted', 'Taunted'), ('encored', 'Encored'), ('tormented', 'Tormented'), ('heal_blocked', 'Heal Blocked'), ('perish_song', 'Perish Song'), ('yawning', 'Yawning'), ('ignited', 'Ignited'), ('immobile', 'Immobile'), ('chaos', 'Chaos'), ('blinded', 'Blinded'), ('acupunctured', 'Acupunctured'), ('imprisoned', 'Imprisoned'), ('tagged', 'Tagged'), ('enfeebled', 'Enfeebled'), ('weakened', 'Weakened'), ('corroded', 'Corroded'), ('interrupted', 'Interrupted')], unique=True)),
                ('category', models.TextField(choices=[('persistent', 'Persistent'), ('volatile', 'Volatile'), ('naruto', 'Naruto Inspired')], db_index=True)),
                ('description', models.TextField(blank=True, default='')),
                ('default_duration', models.PositiveIntegerField(blank=True, help_text='Default duration in rounds. Null means indefinite.', null=True)),
                ('damage_per_turn', models.PositiveIntegerField(default=0, help_text='Damage dealt each turn as 1/16 fractions of max HP.')),
                ('prevents_action', models.BooleanField(default=False, help_text='If True, the Pokemon cannot act while this status is active.')),
                ('modifies_stats', models.JSONField(blank=True, help_text="Dict mapping stat name to float multiplier, e.g. {'attack': 0.5}", null=True)),
                ('disables_healing', models.BooleanField(default=False, help_text='If True, the Pokemon cannot recover HP while this status is active.')),
            ],
            options={
                'verbose_name': 'status effect',
                'verbose_name_plural': 'status effects',
                'ordering': ['category', 'name'],
            },
        ),
    ]
