# Generated by Django 5.0.6 on 2026-03-31 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('effects', '0001_initial'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activestatuseffect',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_statuses', to='game.battleslot'),
        ),
        migrations.AddField(
            model_name='activestatuseffect',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_instances', to='effects.statuseffect'),
        ),
        migrations.AlterUniqueTogether(
            name='activestatuseffect',
            unique_together={('slot', 'status')},
        ),
    ]
