# Generated by Django 5.0.6 on 2026-04-14 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effects', '0002_initial'),
        ('game', '0010_phase2_seeded_applied_by_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='activestatuseffect',
            name='applied_by_slot',
            field=models.ForeignKey(blank=True, help_text='The slot that applied this effect (used for SEEDED drain).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seeded_targets', to='game.battleslot'),
        ),
        migrations.AlterField(
            model_name='statuseffect',
            name='category',
            field=models.TextField(choices=[('persistent', 'Persistent'), ('volatile', 'Volatile'), ('naruto', 'Naruto Inspired'), ('physical', 'Physical State'), ('utility', 'Utility'), ('advanced', 'Advanced')], db_index=True),
        ),
        migrations.AlterField(
            model_name='statuseffect',
            name='name',
            field=models.TextField(choices=[('burned', 'Burned'), ('poisoned', 'Poisoned'), ('badly_poisoned', 'Badly Poisoned'), ('paralyzed', 'Paralyzed'), ('frozen', 'Frozen'), ('asleep', 'Asleep'), ('confused', 'Confused'), ('infatuated', 'Infatuated'), ('flinched', 'Flinched'), ('bound', 'Bound'), ('seeded', 'Seeded'), ('cursed', 'Cursed'), ('nightmare', 'Nightmare'), ('taunted', 'Taunted'), ('encored', 'Encored'), ('tormented', 'Tormented'), ('heal_blocked', 'Heal Blocked'), ('perish_song', 'Perish Song'), ('yawning', 'Yawning'), ('ignited', 'Ignited'), ('immobile', 'Immobile'), ('chaos', 'Chaos'), ('blinded', 'Blinded'), ('acupunctured', 'Acupunctured'), ('imprisoned', 'Imprisoned'), ('tagged', 'Tagged'), ('enfeebled', 'Enfeebled'), ('weakened', 'Weakened'), ('corroded', 'Corroded'), ('interrupted', 'Interrupted'), ('grounded', 'Grounded'), ('airborne', 'Airborne'), ('launched', 'Launched'), ('knockback', 'Knockback'), ('shielded', 'Shielded'), ('hidden', 'Hidden'), ('immune', 'Immune'), ('chain_breaker', 'Chain Breaker'), ('state_locked', 'State Locked')], unique=True),
        ),
    ]
