# Generated by Django 5.0.6 on 2026-05-06 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effects', '0003_phase2_seeded_applied_by_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuseffect',
            name='name',
            field=models.TextField(choices=[('burned', 'Burned'), ('poisoned', 'Poisoned'), ('badly_poisoned', 'Badly Poisoned'), ('paralyzed', 'Paralyzed'), ('frozen', 'Frozen'), ('asleep', 'Asleep'), ('confused', 'Confused'), ('infatuated', 'Infatuated'), ('flinched', 'Flinched'), ('bound', 'Bound'), ('seeded', 'Seeded'), ('cursed', 'Cursed'), ('nightmare', 'Nightmare'), ('taunted', 'Taunted'), ('encored', 'Encored'), ('tormented', 'Tormented'), ('heal_blocked', 'Heal Blocked'), ('perish_song', 'Perish Song'), ('yawning', 'Yawning'), ('ignited', 'Ignited'), ('immobile', 'Immobile'), ('chaos', 'Chaos'), ('blinded', 'Blinded'), ('acupunctured', 'Acupunctured'), ('imprisoned', 'Imprisoned'), ('tagged', 'Tagged'), ('enfeebled', 'Enfeebled'), ('weakened', 'Weakened'), ('corroded', 'Corroded'), ('interrupted', 'Interrupted'), ('grounded', 'Grounded'), ('airborne', 'Airborne'), ('launched', 'Launched'), ('knockback', 'Knockback'), ('shielded', 'Shielded'), ('hidden', 'Hidden'), ('immune', 'Immune'), ('chain_breaker', 'Chain Breaker'), ('state_locked', 'State Locked'), ('charging', 'Charging')], unique=True),
        ),
    ]
