# Generated by Django 5.0.6 on 2026-04-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_ryo_last_daily_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pity_full_art',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='pity_holographic',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='pity_secret_rare',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
