# Generated by Django 5.0.6 on 2026-04-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_badge_tracking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trainer_level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='trainer_xp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='trainer_xp_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='trainer_xp_today',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
