# Generated by Django 5.0.6 on 2026-04-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_trainer_level_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='candy_golden_apple',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='candy_sweet_berry',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='candy_trail_mix',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
