# Generated by Django 5.0.6 on 2026-04-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_candy_inventory_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="training_slot_upgrade_level",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
