# Generated by Django 5.0.6 on 2026-05-07 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_arcade_daily_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='guild_quests_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='GameAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(db_index=True)),
                ('ryo_reward', models.PositiveIntegerField(default=0)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'game achievement',
                'verbose_name_plural': 'game achievements',
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'key')},
            },
        ),
    ]
