# Generated by Django 5.0.6 on 2026-05-07 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_achievements_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='guide_step',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
