# Generated by Django 5.0.6 on 2026-04-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quests", "0003_questtemplate_condition_meta"),
    ]

    operations = [
        migrations.AddField(
            model_name="questtemplate",
            name="reward_candy_qty",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Optional candy reward quantity.",
            ),
        ),
        migrations.AddField(
            model_name="questtemplate",
            name="reward_candy_type",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional candy reward type (trail_mix, sweet_berry, golden_apple).",
            ),
        ),
        migrations.AddField(
            model_name="userquest",
            name="progress_meta",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
