# Generated by Django 5.0.6 on 2026-05-06 00:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0006_seed_minigame_quest_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userquest',
            name='unique_user_quest_period',
        ),
        migrations.AlterField(
            model_name='questtemplate',
            name='condition',
            field=models.TextField(choices=[('win_battles', 'Win N Battles'), ('achieve_combo', 'Achieve N-Link Combo Chain'), ('open_packs', 'Open N Sticker Packs'), ('complete_expeditions', 'Complete N Expeditions'), ('bond_pokemon', 'Bond N Pokémon on Expeditions'), ('play_silhouette', 'Play N Silhouette Tower Runs'), ('play_memory', 'Clear N Memory Boards'), ('play_loteria', 'Play N Loteria Rounds')]),
        ),
        migrations.AlterUniqueTogether(
            name='userquest',
            unique_together={('user', 'template', 'period_key')},
        ),
    ]
