# Generated by Django 5.0.6 on 2026-03-31 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('effects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'verbose_name': 'Pokemon type',
                'verbose_name_plural': 'Pokemon types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('power', models.PositiveIntegerField(default=0)),
                ('accuracy', models.PositiveIntegerField(default=100)),
                ('pp', models.PositiveIntegerField(default=10)),
                ('description', models.TextField(blank=True, default='')),
                ('applies_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_by_moves', to='effects.statuseffect')),
                ('trigger_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggers_moves', to='effects.statuseffect')),
                ('move_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moves', to='pokemon.pokemontype')),
            ],
            options={
                'verbose_name': 'move',
                'verbose_name_plural': 'moves',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('base_hp', models.PositiveIntegerField(default=45)),
                ('base_attack', models.PositiveIntegerField(default=45)),
                ('base_defense', models.PositiveIntegerField(default=45)),
                ('base_sp_attack', models.PositiveIntegerField(default=45)),
                ('base_sp_defense', models.PositiveIntegerField(default=45)),
                ('base_speed', models.PositiveIntegerField(default=45)),
                ('sprite_url', models.TextField(blank=True, default='')),
                ('pokedex_number', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('moves', models.ManyToManyField(blank=True, related_name='learned_by', to='pokemon.move')),
                ('primary_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_pokemon', to='pokemon.pokemontype')),
                ('secondary_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_pokemon', to='pokemon.pokemontype')),
            ],
            options={
                'verbose_name': 'pokemon',
                'verbose_name_plural': 'pokemon',
                'ordering': ['pokedex_number', 'name'],
            },
        ),
    ]
