# Generated by Django 5.0.6 on 2026-04-02 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_merge_0003_move_tactical_fields_0003_team_teamslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownedpokemon',
            name='training_duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownedpokemon',
            name='training_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownedpokemon',
            name='training_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
