# Generated by Django 5.0.6 on 2026-04-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0007_ownedpokemon_move_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='slot_type',
            field=models.TextField(choices=[('standard', 'Basic Technique'), ('chase', 'Chase Technique'), ('special', 'Secret Technique'), ('support', 'Support Technique'), ('passive', 'Ninja Trait')], db_index=True, default='standard'),
        ),
        migrations.AlterField(
            model_name='speciesmovepool',
            name='slot_type',
            field=models.TextField(choices=[('standard', 'Basic Technique'), ('chase', 'Chase Technique'), ('special', 'Secret Technique'), ('support', 'Support Technique'), ('passive', 'Ninja Trait')], db_index=True, default='standard', help_text='Which battle slot this move occupies for this species.'),
        ),
    ]
