# Generated by Django 5.0.6 on 2026-04-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0013_rename_base_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='chase_condition',
            field=models.TextField(blank=True, db_index=True, help_text='Physical state the target must be in for this Chase move to trigger (airborne / launched / knockback / grounded). Null = no restriction.', null=True),
        ),
        migrations.AlterField(
            model_name='chakraelement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='heldeffect',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='move',
            name='slot_type',
            field=models.TextField(choices=[('standard', 'Basic Technique'), ('chase', 'Chase Technique'), ('mystery', 'Mystery'), ('passive_1', 'Passive 1'), ('passive_2', 'Passive 2')], db_index=True, default='standard'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='primary_role',
            field=models.TextField(blank=True, choices=[('burst', 'Burst'), ('combo', 'Combo'), ('tank', 'Tank'), ('support', 'Support'), ('control', 'Control')], db_index=True, default='burst', help_text='Tactical identity: determines build flavor and pool curation.'),
        ),
        migrations.AlterField(
            model_name='speciesmovepool',
            name='role_tag',
            field=models.TextField(blank=True, choices=[('burst', 'Burst'), ('combo', 'Combo'), ('tank', 'Tank'), ('support', 'Support'), ('control', 'Control')], db_index=True, default='', help_text='Tactical build this pool entry belongs to (optional). Allows multi-build pools later.'),
        ),
        migrations.AlterField(
            model_name='speciesmovepool',
            name='slot_type',
            field=models.TextField(choices=[('standard', 'Basic Technique'), ('chase', 'Chase Technique'), ('mystery', 'Mystery'), ('passive_1', 'Passive 1'), ('passive_2', 'Passive 2')], db_index=True, default='standard', help_text='Which battle slot this move occupies for this species.'),
        ),
    ]
