# Generated by Django 5.0.6 on 2026-04-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0016_backfill_gen1_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='chakra_cost',
            field=models.PositiveSmallIntegerField(default=0, help_text='Chakra required to activate this mystery move (0 = free). Tiers: 20 light / 35 standard / 50 heavy / 80 forbidden. Chase and support moves always stay at 0.'),
        ),
    ]
