# Generated by Django 5.0.6 on 2026-05-07 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0017_move_chakra_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='learnset',
            field=models.JSONField(blank=True, default=list, help_text='PokeAPI learnset. List of dicts: {name, type, power, accuracy, pp, damage_class, learn_methods: [level-up|machine|egg|tutor], level}.'),
        ),
    ]
