# Generated by Django 5.0.6 on 2026-05-06 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_loteria_room_pause_budget'),
        ('ranked', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchmakingentry',
            name='battle',
            field=models.ForeignKey(blank=True, help_text='Set when this entry has been matched into a battle.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matchmaking_entries', to='game.battle'),
        ),
        migrations.AlterField(
            model_name='matchmakingentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='matchmakingentry',
            name='rank_points',
            field=models.PositiveIntegerField(default=0, help_text="Snapshot of the player's rank_points at queue join time."),
        ),
        migrations.AlterField(
            model_name='rankedprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rankedprofile',
            name='sub_tier',
            field=models.PositiveSmallIntegerField(default=3, help_text='Sub-division within a tier: 1 = highest, 3 = lowest.'),
        ),
        migrations.AlterField(
            model_name='rankedseason',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rankedseason',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False, help_text='Only one season should be active at a time.'),
        ),
    ]
