# Generated by Django 5.0.6 on 2026-03-31 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity', models.TextField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('holographic', 'Holographic'), ('full_art', 'Full Art'), ('secret_rare', 'Secret Rare')], db_index=True, default='common')),
                ('variant', models.TextField(choices=[('base', 'Base'), ('shiny', 'Shiny'), ('battle_scene', 'Battle Scene'), ('chibi', 'Chibi'), ('manga_panel', 'Manga Panel'), ('full_illustration', 'Full Illustration')], db_index=True, default='base')),
                ('is_trading', models.BooleanField(db_index=True, default=False)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_showcase', models.BooleanField(default=False, help_text="Pinned to the player's profile showcase (max 6).")),
                ('awarded_from', models.TextField(blank=True, default='', help_text='How this sticker was obtained: catch, level_up, combo_win, pack, craft')),
                ('date_caught', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'sticker',
                'verbose_name_plural': 'stickers',
                'ordering': ['-date_caught'],
            },
        ),
        migrations.CreateModel(
            name='StickerAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'sticker album',
                'verbose_name_plural': 'sticker albums',
            },
        ),
        migrations.CreateModel(
            name='StickerPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened', models.BooleanField(default=False)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'sticker pack',
                'verbose_name_plural': 'sticker packs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'trade history',
                'verbose_name_plural': 'trade histories',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('looking_for_note', models.TextField(blank=True, default='', help_text='Free-text note describing what the offerer is looking for.')),
                ('status', models.TextField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'trade offer',
                'verbose_name_plural': 'trade offers',
                'ordering': ['-created_at'],
            },
        ),
    ]
