# Generated by Django 5.0.6 on 2026-03-31 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pokemon', '0001_initial'),
        ('stickers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stickers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sticker',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stickers', to='pokemon.pokemon'),
        ),
        migrations.AddField(
            model_name='stickeralbum',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sticker_album', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stickeralbum',
            name='showcase_stickers',
            field=models.ManyToManyField(blank=True, related_name='showcased_in_albums', to='stickers.sticker'),
        ),
        migrations.AddField(
            model_name='stickerpack',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sticker_packs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stickerpack',
            name='stickers',
            field=models.ManyToManyField(blank=True, related_name='from_pack', to='stickers.sticker'),
        ),
        migrations.AddField(
            model_name='tradehistory',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades_initiated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tradehistory',
            name='sticker_given',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='given_in_trade_history', to='stickers.sticker'),
        ),
        migrations.AddField(
            model_name='tradehistory',
            name='sticker_received',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_in_trade_history', to='stickers.sticker'),
        ),
        migrations.AddField(
            model_name='tradehistory',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tradeoffer',
            name='offered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_offers_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tradeoffer',
            name='offered_sticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_in_trades', to='stickers.sticker'),
        ),
        migrations.AddField(
            model_name='tradeoffer',
            name='offered_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_offers_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tradeoffer',
            name='requested_pokemon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_in_trades', to='pokemon.pokemon'),
        ),
        migrations.AddField(
            model_name='tradeoffer',
            name='requested_sticker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_in_trades', to='stickers.sticker'),
        ),
        migrations.AddField(
            model_name='tradehistory',
            name='offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='stickers.tradeoffer'),
        ),
        migrations.AddIndex(
            model_name='sticker',
            index=models.Index(fields=['owner', 'pokemon', 'rarity', 'variant'], name='stickers_st_owner_i_1f4892_idx'),
        ),
    ]
