# Generated by Django 5.0.6 on 2026-04-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='variant',
            field=models.TextField(choices=[('base', 'Base'), ('shiny', 'Shiny'), ('battle_scene', 'Battle Scene'), ('chibi', 'Chibi'), ('manga_panel', 'Manga Panel'), ('full_illustration', 'Full Illustration'), ('anime', 'Anime')], db_index=True, default='base'),
        ),
    ]
