# Generated by Django 5.0.6 on 2026-04-15 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0014_move_chase_condition'),
        ('stickers', '0004_albumcompletionreward'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.TextField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('holographic', 'Holographic'), ('prismatic', 'Prismatic')], db_index=True)),
                ('effect_category', models.TextField(blank=True, default='', help_text='trigger_amplifier | chakra_engine | cooldown_reducer | threshold_heal | combo_extender | type_burst | status_chain')),
                ('effect_params', models.JSONField(default=dict, help_text='Serialised effect parameters (value, condition, target, etc.)')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'badge',
                'verbose_name_plural': 'badges',
            },
        ),
        migrations.CreateModel(
            name='OwnedBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipped_slot', models.PositiveSmallIntegerField(blank=True, help_text='Active badge slot (1, 2, or 3). Null means unequipped.', null=True)),
                ('crafted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'owned badge',
                'verbose_name_plural': 'owned badges',
            },
        ),
        migrations.CreateModel(
            name='RegionalAlbumPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.TextField(db_index=True)),
                ('rarity', models.TextField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('holographic', 'Holographic'), ('full_art', 'Full Art'), ('secret_rare', 'Secret Rare')], db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reward_claimed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'regional album page',
                'verbose_name_plural': 'regional album pages',
            },
        ),
        migrations.RemoveConstraint(
            model_name='albumcompletionreward',
            name='unique_album_completion_reward',
        ),
        migrations.AddField(
            model_name='sticker',
            name='is_album_placed',
            field=models.BooleanField(db_index=True, default=False, help_text='True when this sticker is placed in a regional album page (soul-bound).'),
        ),
        migrations.AlterUniqueTogether(
            name='albumcompletionreward',
            unique_together={('user', 'reward_type', 'pokemon')},
        ),
        migrations.AddField(
            model_name='badge',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='pokemon.pokemon'),
        ),
        migrations.AddField(
            model_name='ownedbadge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='stickers.badge'),
        ),
        migrations.AddField(
            model_name='ownedbadge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_badges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='regionalalbumpage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_album_pages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='badge',
            unique_together={('pokemon', 'tier')},
        ),
        migrations.AlterUniqueTogether(
            name='ownedbadge',
            unique_together={('user', 'badge')},
        ),
        migrations.AlterUniqueTogether(
            name='regionalalbumpage',
            unique_together={('user', 'region', 'rarity')},
        ),
    ]
