# Generated by Django 5.0.6 on 2026-04-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0005_album_placed_regional_badges'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.TextField(db_index=True)),
                ('page_number', models.PositiveSmallIntegerField()),
                ('dex_start', models.PositiveIntegerField()),
                ('dex_end', models.PositiveIntegerField()),
                ('location_name', models.TextField()),
                ('bg_image_name', models.TextField(blank=True, default='', help_text='Filename under static/img/albums/. Empty = use CSS gradient fallback.')),
            ],
            options={
                'verbose_name': 'album page',
                'verbose_name_plural': 'album pages',
                'ordering': ['region', 'page_number'],
                'unique_together': {('region', 'page_number')},
            },
        ),
    ]
