# Generated by Django 5.0.6 on 2026-05-06 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0009_rename_variants_and_rarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalalbumpage',
            name='rarity',
            field=models.TextField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('prismatic', 'Prismatic'), ('full_art', 'Full Art'), ('secret_rare', 'Secret Rare')], db_index=True),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='rarity',
            field=models.TextField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('prismatic', 'Prismatic'), ('full_art', 'Full Art'), ('secret_rare', 'Secret Rare')], db_index=True, default='common'),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='variant',
            field=models.TextField(choices=[('base', 'Base'), ('shiny', 'Shiny'), ('battle_scene', 'Battle Scene'), ('watercolor', 'Watercolor'), ('sketch', 'Sketch'), ('neon_glow', 'Neon Glow'), ('burn_scroll', 'Burn Scroll'), ('tv_90s', '90s TV'), ('holographic', 'Holographic'), ('color_swap', 'Color Swap'), ('glitter', 'Glitter'), ('chrome', 'Chrome'), ('cartoon', 'Cartoon'), ('anime', 'Anime')], db_index=True, default='base'),
        ),
        migrations.AlterField(
            model_name='stickerpack',
            name='pack_type',
            field=models.TextField(choices=[('standard', 'Standard Pack'), ('bundle', 'Bundle Pack'), ('gen1', 'Kanto Pack (Gen 1)'), ('gen2', 'Johto Pack (Gen 2)'), ('gen3', 'Hoenn Pack (Gen 3)'), ('gen4', 'Sinnoh Pack (Gen 4)'), ('gen5', 'Unova Pack (Gen 5)'), ('gen6', 'Kalos Pack (Gen 6)'), ('gen7', 'Alola Pack (Gen 7)'), ('gen8', 'Galar Pack (Gen 8)')], db_index=True, default='standard', help_text='standard = 5 stickers; bundle = 10 stickers with improved rarity odds.'),
        ),
    ]
