# Generated by Django 5.0.6 on 2026-03-31 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('setup', 'Setup'), ('active', 'Active'), ('finished', 'Finished')], db_index=True, default='setup')),
                ('current_round', models.PositiveIntegerField(default=1)),
                ('max_combo_chain', models.PositiveIntegerField(default=0, help_text='Longest combo chain achieved in this battle.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'battle',
                'verbose_name_plural': 'battles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BattleAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_dealt', models.IntegerField(default=0)),
                ('is_combo_triggered', models.BooleanField(default=False)),
                ('order_in_chain', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'battle action',
                'verbose_name_plural': 'battle actions',
                'ordering': ['created_at', 'order_in_chain'],
            },
        ),
        migrations.CreateModel(
            name='BattleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('message', models.TextField()),
                ('log_type', models.TextField(choices=[('action', 'Action'), ('combo', 'Combo'), ('status', 'Status'), ('faint', 'Faint'), ('info', 'Info')], db_index=True, default='info')),
                ('chain_position', models.PositiveIntegerField(blank=True, help_text='Position in combo chain, if applicable.', null=True)),
                ('chain_total', models.PositiveIntegerField(blank=True, help_text='Total chain length when this was logged.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'battle log',
                'verbose_name_plural': 'battle logs',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BattleRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'battle round',
                'verbose_name_plural': 'battle rounds',
                'ordering': ['round_number'],
            },
        ),
        migrations.CreateModel(
            name='BattleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(help_text='Slot position 1–6 on the team.')),
                ('level', models.PositiveSmallIntegerField(default=50)),
                ('current_hp', models.PositiveIntegerField()),
                ('max_hp', models.PositiveIntegerField()),
                ('is_fainted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'battle slot',
                'verbose_name_plural': 'battle slots',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='BattleTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'battle team',
                'verbose_name_plural': 'battle teams',
            },
        ),
    ]
