# Generated by Django 5.0.6 on 2026-03-31 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('effects', '0002_initial'),
        ('game', '0001_initial'),
        ('pokemon', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='player_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_player_one', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='battle',
            name='player_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battles_as_player_two', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='battle',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battles_won_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='battleaction',
            name='move',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='battle_actions', to='pokemon.move'),
        ),
        migrations.AddField(
            model_name='battleaction',
            name='status_applied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='effects.statuseffect'),
        ),
        migrations.AddField(
            model_name='battlelog',
            name='battle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='game.battle'),
        ),
        migrations.AddField(
            model_name='battleround',
            name='battle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='game.battle'),
        ),
        migrations.AddField(
            model_name='battleaction',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='game.battleround'),
        ),
        migrations.AddField(
            model_name='battleslot',
            name='last_move_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pokemon.move'),
        ),
        migrations.AddField(
            model_name='battleslot',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='battle_slots', to='pokemon.pokemon'),
        ),
        migrations.AddField(
            model_name='battleaction',
            name='attacker_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_as_attacker', to='game.battleslot'),
        ),
        migrations.AddField(
            model_name='battleaction',
            name='target_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_as_target', to='game.battleslot'),
        ),
        migrations.AddField(
            model_name='battleteam',
            name='battle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='game.battle'),
        ),
        migrations.AddField(
            model_name='battleteam',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='battleslot',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='game.battleteam'),
        ),
        migrations.AlterUniqueTogether(
            name='battleround',
            unique_together={('battle', 'round_number')},
        ),
        migrations.AlterUniqueTogether(
            name='battleteam',
            unique_together={('battle', 'owner')},
        ),
        migrations.AlterUniqueTogether(
            name='battleslot',
            unique_together={('team', 'position')},
        ),
    ]
