# Generated by Django 5.0.6 on 2026-03-31 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='ai_difficulty',
            field=models.TextField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium'),
        ),
        migrations.AddField(
            model_name='battle',
            name='is_ai_battle',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
