# Generated by Django 5.0.6 on 2026-04-02 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_battleslot_owned_pokemon'),
        ('pokemon', '0008_alter_move_slot_type_alter_speciesmovepool_slot_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battleslot',
            name='grid_position',
            field=models.TextField(choices=[('front_left', 'Front Left'), ('front_right', 'Front Right'), ('back_left', 'Back Left'), ('back_right', 'Back Right'), ('bench_1', 'Bench 1'), ('bench_2', 'Bench 2')], default='front_left', help_text='Named grid cell: front_left/front_right/back_left/back_right/bench_1/bench_2.'),
        ),
        migrations.AlterField(
            model_name='battleslot',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='True if the slot is on the field (not on the bench).'),
        ),
        migrations.AlterField(
            model_name='battleslot',
            name='selected_move',
            field=models.ForeignKey(blank=True, help_text='The move the player has chosen to use; persists until changed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pokemon.move'),
        ),
        migrations.AlterField(
            model_name='battleslot',
            name='selected_target',
            field=models.ForeignKey(blank=True, help_text='The target slot the player has chosen; persists until changed or invalidated.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.battleslot'),
        ),
        migrations.AlterField(
            model_name='movecooldown',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
