# Generated by Django 5.0.6 on 2026-04-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_battleslot_stat_expansion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battleslot',
            name='grid_position',
            field=models.TextField(choices=[('front_left', 'Front Left'), ('front_center', 'Front Center'), ('front_right', 'Front Right'), ('back_left', 'Back Left'), ('back_center', 'Back Center'), ('back_right', 'Back Right'), ('bench_1', 'Bench 1'), ('bench_2', 'Bench 2')], default='front_left', help_text='Named grid cell: front_left/front_right/back_left/back_right/bench_1/bench_2.'),
        ),
        migrations.AlterField(
            model_name='battleslotheldeffect',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
