# Generated by Django 5.0.6 on 2026-04-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_phase3_control_penetration'),
    ]

    operations = [
        migrations.AddField(
            model_name='battleteam',
            name='chakra_pool',
            field=models.PositiveSmallIntegerField(default=0, help_text='Shared team chakra (0–100). Regenerates each round; spent on mystery moves.'),
        ),
    ]
