# Generated by Django 5.0.6 on 2026-04-23 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_battleteam_chakra_pool'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteriaRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_key', models.CharField(db_index=True, max_length=32)),
                ('title', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('finished', 'Finished')], db_index=True, default='waiting', max_length=16)),
                ('round_number', models.PositiveIntegerField(default=1)),
                ('prize_pool_ryo', models.PositiveIntegerField(default=0)),
                ('deck_order', models.JSONField(default=list, help_text='Ordered list of Pokemon ids to deal for this room.')),
                ('called_species_ids', models.JSONField(default=list, help_text='Pokemon ids already called this round.')),
                ('next_tick_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'loteria room',
                'verbose_name_plural': 'loteria rooms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoteriaBoardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_key', models.CharField(db_index=True, max_length=32)),
                ('board_slot', models.PositiveSmallIntegerField(help_text='Saved slot number within this deck (1-3).')),
                ('title', models.CharField(default='Collector Board', max_length=80)),
                ('species_ids', models.JSONField(default=list, help_text='Ordered list of 16 Pokemon ids for the 4x4 board.')),
                ('seeded_by_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loteria_boards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'loteria board template',
                'verbose_name_plural': 'loteria board templates',
                'ordering': ['deck_key', 'board_slot'],
                'unique_together': {('owner', 'deck_key', 'board_slot')},
            },
        ),
        migrations.CreateModel(
            name='LoteriaRoomEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=80)),
                ('board_slot', models.PositiveSmallIntegerField(default=1)),
                ('species_ids', models.JSONField(default=list, help_text='Snapshot of board species ids when the room entry was created.')),
                ('is_npc', models.BooleanField(db_index=True, default=False)),
                ('is_winner', models.BooleanField(db_index=True, default=False)),
                ('reward_ryo', models.PositiveIntegerField(default=0)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('board_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_entries', to='game.loteriaboardtemplate')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='game.loteriaroom')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loteria_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'loteria room entry',
                'verbose_name_plural': 'loteria room entries',
                'ordering': ['entered_at', 'pk'],
            },
        ),
    ]
