# Generated by Django 5.0.6 on 2026-04-23 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0013_loteriaroom_loteriaboardtemplate_loteriaroomentry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="loteriaroom",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_index=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_loteria_rooms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loteriaroom",
            name="mode",
            field=models.CharField(
                choices=[("quick_npc", "Quick Play vs NPC"), ("private", "Private Room")],
                db_index=True,
                default="quick_npc",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="loteriaroom",
            name="npc_count",
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="loteriaroom",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("lobby", "Lobby"),
                    ("active", "Active"),
                    ("finished", "Finished"),
                ],
                db_index=True,
                default="draft",
                max_length=16,
            ),
        ),
    ]
