# Generated by Django 5.0.6 on 2026-04-28 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_loteria_private_rooms_and_participants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteriaPrizeClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_key', models.CharField(db_index=True, max_length=32)),
                ('pattern_label', models.CharField(max_length=48)),
                ('reward_ryo', models.PositiveIntegerField(default=0)),
                ('shared_winner_count', models.PositiveSmallIntegerField(default=1)),
                ('winner_names_snapshot', models.JSONField(default=list, help_text='Display names that shared this pattern prize.')),
                ('claimed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prize_claims', to='game.loteriaroomentry')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prize_claims', to='game.loteriaroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loteria_prize_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'loteria prize claim',
                'verbose_name_plural': 'loteria prize claims',
                'ordering': ['claimed_at', '-created_at', 'pk'],
                'unique_together': {('entry', 'pattern_key')},
            },
        ),
    ]
