# Generated by Django 5.0.6 on 2026-04-16 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pokemon', '0014_move_chase_condition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(help_text="Stable slug, e.g. 'meadow_route'", unique=True)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, default='')),
                ('flavor_intro', models.TextField(blank=True, default='', help_text='Text shown when entering the zone.')),
                ('flavor_walking', models.TextField(blank=True, default='', help_text='Short text shown between encounters.')),
                ('cost', models.PositiveIntegerField(help_text='Ryo cost per expedition run.')),
                ('encounters_per_run', models.PositiveIntegerField(default=5)),
                ('min_trainer_level', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('bg_gradient', models.TextField(blank=True, default='', help_text='CSS gradient for zone background.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExpeditionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('encounters_total', models.PositiveIntegerField()),
                ('encounters_used', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedition_sessions', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='expedition.zone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EncounterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_bond_rate', models.PositiveIntegerField(help_text='Random 15–90 before candy.')),
                ('candy_used', models.TextField(blank=True, default='', help_text='Candy type or empty.')),
                ('final_bond_rate', models.PositiveIntegerField(help_text='After candy, capped at 90.')),
                ('bonded', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owned_pokemon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounter_origin', to='pokemon.ownedpokemon')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounter_logs', to='pokemon.pokemon')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='expedition.expeditionsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZoneSpawnEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(default=10, help_text='Relative spawn probability.')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_spawns', to='pokemon.pokemon')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spawns', to='expedition.zone')),
            ],
            options={
                'ordering': ['-weight', 'species__name'],
                'unique_together': {('zone', 'species')},
            },
        ),
    ]
